name: Dependabot Change Note

on:
  push:
    branches:
      - 'dependabot/**'

jobs:
  changenote:
    name: Dependabot Change Note
    uses: rmartin16/.github-beeware-test/.github/shared_workflows/dependabot-changenote.yml@main
    secrets: inherit
