name: Dependabot Change Note
on:
  push:
    branches:
      - 'dependabot/**'

permissions:
  pull-requests: write

jobs:
  changenote:
    name: Dependabot Change Note
    if: github.actor == 'dependabot[bot]'
    uses: rmartin16/.github-beeware-test/.github/workflows/dependabot-changenote.yml@main
    secrets: inherit
